# Generated by Django 4.2.6 on 2023-11-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='sanitary_sector',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
