# Generated by Django 4.2.6 on 2023-11-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_sanitary_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='sanitary_sector',
            new_name='sanitary_industry_type',
        ),
    ]
