# Generated by Django 4.2.7 on 2023-11-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='latitude',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='longitude',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
