# Generated by Django 4.2.7 on 2023-11-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_rating'),
        ('restaurants', '0004_alter_restaurant_parcel_address_and_more'),
    ]

    operations = [
    ]
