# Generated by Django 4.2.7 on 2023-11-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_lunch_recommendation',
            new_name='is_lunch_recommend',
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
