# Generated by Django 4.2.7 on 2023-11-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_latitude_alter_user_longitude'),
        ('users', '0002_rename_is_lunch_recommendation_user_is_lunch_recommend_and_more'),
    ]

    operations = [
    ]
